// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOuSRxd_h0-AoaqlTo5nYrdjW5mjQISEI',
    appId: '1:369170877451:web:732cce6fbfbff596054b0e',
    messagingSenderId: '369170877451',
    projectId: 'otokutuphane-5d32a',
    authDomain: 'otokutuphane-5d32a.firebaseapp.com',
    storageBucket: 'otokutuphane-5d32a.firebasestorage.app',
    measurementId: 'G-XK0R9X5W6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6OIXYbLVi_wWbr1sg1WrbT0PnVfyysEQ',
    appId: '1:369170877451:android:eeca5503a913f8970a2c66',
    messagingSenderId: '369170877451',
    projectId: 'otokutuphane-5d32a',
    storageBucket: 'otokutuphane-5d32a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPjJ1AkddMxz1N6hFQwasSXdgxvxK3EOA',
    appId: '1:369170877451:ios:d1ae7a72b609e2d00a2c66',
    messagingSenderId: '369170877451',
    projectId: 'otokutuphane-5d32a',
    storageBucket: 'otokutuphane-5d32a.firebasestorage.app',
    iosBundleId: 'com.example.otokutuphane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPjJ1AkddMxz1N6hFQwasSXdgxvxK3EOA',
    appId: '1:369170877451:ios:d1ae7a72b609e2d00a2c66',
    messagingSenderId: '369170877451',
    projectId: 'otokutuphane-5d32a',
    storageBucket: 'otokutuphane-5d32a.firebasestorage.app',
    iosBundleId: 'com.example.otokutuphane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOuSRxd_h0-AoaqlTo5nYrdjW5mjQISEI',
    appId: '1:369170877451:web:676a830149b7458e0a2c66',
    messagingSenderId: '369170877451',
    projectId: 'otokutuphane-5d32a',
    authDomain: 'otokutuphane-5d32a.firebaseapp.com',
    storageBucket: 'otokutuphane-5d32a.firebasestorage.app',
    measurementId: 'G-XK0R9X5W6J',
  );
}
